server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: content-service
          uri: http://${CONTENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/content/
            - Method=GET
            - Query=roomname
          filters:
            - SetPath=/api/content/
        - id: content-service-post
          uri: http://${CONTENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/content
            - Method=POST
          filters:
            - SetPath=/api/content/create
        - id: content-service-put
          uri: http://${CONTENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/content
            - Method=PUT
          filters:
            - SetPath=/api/content/update
        - id: content-service-delete
          uri: http://${CONTENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/content/
            - Method=DELETE
            - Query=roomname
          filters:
            - SetPath=/api/content/delete/
        - id: reservation-service-allbyname
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reservations/
            - Method=GET
            - Query=roomname
          filters:
            - SetPath=/api/reservation/allbyroomname/
        - id: reservation-service-all
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reservations
            - Method=GET
          filters:
            - SetPath=/api/reservation
        - id: reservation-service-post
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reservation
            - Method=POST
          filters:
            - SetPath=/api/reservation/create
        - id: reservation-service-delete
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reservation/
            - Method=DELETE
            - Query=id
          filters:
            - SetPath=/api/reservation/delete/
        - id: reservation-service-deleteall
          uri: http://${RESERVATION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reservations/
            - Method=DELETE
            - Query=roomname
          filters:
            - SetPath=/api/reservation/deleteall/
        - id: classroom-service
          uri: http://${CLASSROOM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/classroom/
            - Method=GET
            - Query=roomname
          filters:
            - SetPath=/api/classroom/
        - id: classroom-service-all
          uri: http://${CLASSROOM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/classrooms
            - Method=GET
          filters:
            - SetPath=/api/classroom/all
        - id: classroom-service-create
          uri: http://${CLASSROOM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/classroom
            - Method=POST
          filters:
            - SetPath=/api/classroom/create
        - id: classroom-service-delete
          uri: http://${CLASSROOM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/classroom/
            - Method=DELETE
            - Query=roomname
          filters:
            - SetPath=/api/classroom/delete/
